version: '3'

services:
  db:
    container_name: mysqldb
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=db_test
      - MYSQL_ROOT_PASSWORD=unroot
    ports:
      - 3309:3306
    volumes:
      - ${HOME}/blog:/var/lib/mysql/
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sns,sqs,dynamodb,s3
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"